apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: default
  labels:
    app: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: springboot:1.14.2
        ports:
        - containerPort: 80
